# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='s_type',
            new_name='sensor_type',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor'),
        ),
    ]
