# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20171006_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
