# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20171006_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
    ]
