# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20171011_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='name',
            field=models.CharField(default='act1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[(b'WL', b'Water Level'), (b'Temp', b'Temperature'), (b'SM', b'Soil Moisture'), (b'HDT', b'Humidity'), (b'RS', b'RainSensor')], default=b'Temp', max_length=20),
        ),
    ]
