# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('U', 'USER'), ('P', 'PLANT')], default='U', max_length=2),
        ),
    ]
