# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='alias',
            field=models.CharField(default='', max_length=20),
        ),
    ]
