# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='alias',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
