# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20171006_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='alias',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
