# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20171006_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='lat',
            field=models.FloatField(default=13.5115),
        ),
        migrations.AddField(
            model_name='plant',
            name='lon',
            field=models.FloatField(default=80.0144),
        ),
    ]
